include::attributes.adoc[]

:toc:

== About `autotest-ca`

`autotest-ca` is a tool to test `ca_web` in an automated fashion.

You can access the full documentation of this project at https://backstage.test.musubu.co.in/docs/default/Component/autotest-ca[autotest-ca@backstage/techdocs].
Backstage portal of this project is found at https://backstage.test.musubu.co.in/catalog/default/component/autotest-ca[autotest-ca@backstage]

== On-boarding the Project

Check https://github.com/moneyforward/autotest-ca/wiki/developmentGuide[developmentGuide] for more detal.

=== Preparation

You need to install `python3.12` and `trcli` (TestRail CLI client) beforehand.

.Installing `python3.12`
----
$ brew install python3.12
----

.Installing `trcli`
----
$ pip install trcli
----
For more detail, check https://support.testrail.com/hc/en-us/articles/7146548750868-Overview-and-installation#InstallingtheTestRailCLI[TestRail CLI].



=== Bootstrapping: Setting Up Development Environment

Clone the repository:

[source, bash]
----
$ git clone https://github.com/moneyforward/autotest-ca.git
----

Then `cd` to the directory:

[source, bash]
----
$ cd autotest-ca
----

In the project root directory, run:

[source, bash]
----
$ ./bootstrap.sh
----

If this step succeeds, the script will print something like following and should exit with `0`.

----
We are erasing the old .dependencies
pass: <is_git_installed>
---
FAILED CHECKS: 0
BEGIN: BOOTSTRAP
[BOOTSTRAP] Initialized empty Git repository in /Users/ukai.hiroshi/Documents/github/moneyforward/autotest-ca/.dependencies/homebrew/.git/

...

  [sdkman:maven] Installing: maven 3.9.6
  [sdkman:maven] Done installing!
  [sdkman:maven]
  [sdkman:maven]
  [sdkman:maven] Setting maven 3.9.6 as default.
END:   sdkman:maven
----

NOTE:: In case you want to re-try the set-up for some reason, in the project root directory please do:
[source, bash]
----
$ sudo rm -fr .dependencies
----
Then, do `./bootstrap.sh`.

[[IDE]]
=== Integrated Development Environment (IDE)

We use *IntelliJ IDEA* for daily development.
You can use either Community or Ultimate edition.
For SDET(FW) or SDET(PM), Ultimate edition is recommended.

You can just open a test class such as `VisitAllMenuItemsTest.java` and run it with the "Play" button (a green triangle) to run it.

You can request "Ultimate"'s license here: https://join.slack.com/share/enQtNzUxMDM3NDQ5MjAwMi00ZWI3NmU2ZjZiYjEzN2Y2OGNiOGE0NDA4NDIzNDEyNzljYmMwNTI1NjRhMDk1YzVhOWJmNTRlYjRlZTkwMTUx[contact_cio_manged-tools] slack channel.

=== Playing with `./build.sh`

`build.sh` is a very thin wrapper script of `make` command.
It only defines environment variables assumed by the targets defined in `Makefile`, then executes `make` command with arguments passed to itself.

You can skip this part and just open the directory to which you cloned the source code with <<IDE>>.

Still, it is important to define development tasks in the `Makefile` because it allows us to automate and integrate them into CI environment.


==== Building the Executable.

Run the following command.

[source, bash]
----
$ ./build.sh build
----

==== Running the Tests

To run all tests for the SUT, do:

[source, bash]
----
$ ./build.sh run
----

It will show log like following.

[source, bash]
----
java -jar ca_web/target/autotest-caweb.jar -q 'classname:~.*' run
Running tests in:[jp.co.moneyforward.autotest.ca_web.tests.bankaccount.BankConnectingTest]

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2024-06-27T16:15:51,117 [main] INFO  jp.co.moneyforward.autotest.framework.action.ActionComposer [] - ENTERING: :Navigate[https://accounting-stg1.ebisubook.com/]
2024-06-27T16:15:52,655 [main] INFO  jp.co.moneyforward.autotest.framework.action.ActionComposer [] - LEAVING:  :Navigate[https://accounting-stg1.ebisubook.com/]
2024-06-27T16:15:52,655 [main] INFO  jp.co.moneyforward.autotest.framework.action.ActionComposer [] - ENTERING: :SendKey[@[placeholder=example@moneyforward.com]][ukai.hiroshi+autotest1@moneyforward.co.jp]
2024-06-27T16:15:52,722 [main] INFO  j
...
----

You will find test results under `target/testResult` directory after execution.

==== Showing a Help

To know what other targets are defined and their usages, just do:

[source, bash]
----
$ ./build.sh
----

This gives you explanations of "public" targets in the `Makefile`, which you are supposed to use in daily developments.

=== Coding Conventions

Coding conventions are defined under `.idea/codeStyles` and `.ideaInspectionProfiles`.
When you want to propose improvements in the style, please open a pull request containing only files under them.

== Contacts

- For developers discussion: https://moneyforward.slack.com/archives/C06RW82AN79[# pj_ca_e2e_test_automation]
- To report a bug, visit: https://app.asana.com/-/desktop_app_link?path=%2F0%2F1206402209253009%2F1206402209253009%3F[Automatic E2E Testing]


== Copyright and license

All Rights Reserved by Money Forward.
